# Neural networks with keras
## 1. Data load

Datasets we are going to use is MNIST. It consists of training set and test set.

X(Image) is encoded by numpy and Y (Label) is array through 1 to 10.

In [1]:
from keras.datasets import mnist
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

Using TensorFlow backend.


11493376/11490434 [==============================] - 24s 2us/step


##### training set

In [2]:
train_images.shape

(60000, 28, 28)

In [3]:
len(train_labels)

60000

In [4]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

##### test set

In [5]:
test_images.shape

(10000, 28, 28)

In [6]:
len(test_labels)

10000

In [7]:
test_labels

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

## 2. Neural networks
### 2.1 Shallow networks

It consists of 1 hidden layer with 512 node and 1 output layer with softmax layer which produce probability of each label.

In [8]:
from keras import models
from keras import layers

network  = models.Sequential()
network.add(layers.Dense(512, activation='relu', input_shape=(28*28,)))
network.add(layers.Dense(10, activation='softmax'))

### 2.2 Compile

In compile step, we have to define three things, loss function, optimizer and metric to assess model.

In [9]:
network.compile(optimizer='rmsprop',
                loss='categorical_crossentropy',
                metrics=['accuracy'])

## 3. Feed data
### 3.1 Preprocess
##### For x
Before we feed data into neural networks, we need to adjust the number of pixel to 0 to 1 by dividing with 255, and 

change the array (60000, 28, 28) to (60000, 28*28)

In [10]:
train_images = train_images.reshape((60000, 28*28))
train_images = train_images/255

test_images = test_images.reshape((10000, 28*28))
test_images = test_images/255

##### For y
For y, we need to encode it to categorical type. (one-hot encoding)

In [11]:
from keras.utils import to_categorical

train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

In [12]:
train_labels

array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.]], dtype=float32)

In [13]:
test_labels

array([[0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

### 3.2 Train (fit)

In [14]:
network.fit(train_images, train_labels, epochs=5, batch_size=128)

Epoch 1/5
60000/60000 [==============================] - 8s 131us/step - loss: 0.2571 - acc: 0.9252 1s - loss: 0 - ETA: 0s - loss: 0.2602 - acc: 0.924 - ETA: 0s - loss: 0.2590 - acc: 0.9
Epoch 2/5
60000/60000 [==============================] - 8s 126us/step - loss: 0.1049 - acc: 0.9691 3s - l
Epoch 3/5
60000/60000 [==============================] - 8s 130us/step - loss: 0.0691 - acc: 0.9790
Epoch 4/5
60000/60000 [==============================] - 8s 126us/step - loss: 0.0499 - acc: 0.9854
Epoch 5/5
60000/60000 [==============================] - 8s 129us/step - loss: 0.0377 - acc: 0.9884


### 3.3 Test

In [15]:
test_loss, test_acc = network.evaluate(test_images, test_labels)

10000/10000 [==============================] - 1s 83us/step


In [17]:
print('test_acc:', test_acc)

test_acc: 0.9804
